sgammon/rules_graalvm

MODULE.bazel.lock, docs/api/BUILD.bazel, docs/api/defs.md, graalvm/BUILD.bazel, graalvm/nativeimage/BUILD.bazel, internal/BUILD.bazel
Moves docs targets to the `docs` root, so they don't surface downstream for Bzlmod users.
- fix: move doc targets, recommended in bazelbuild/bazel-central-registry#836
- chore: update module lock
- chore: public visibility for `bzl_library` targets (downstream docs)
(thank you @fmeum!)
=> fix(docs): move doc targets to `docs` root

internal/native_image/rules.bzl
Fix for this error seen in CI:
```
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 77: bazel-out/x64_windows-fastbuild/bin/src/main/protobuf/libdeps_proto-speed.jar:bazel-out/x64_windows-fastbuild/bin/external/com_google_protobuf/java/core/libcore.jar:bazel-out/x64_windows-fastbuild/bin/external/com_google_protobuf/java/core/liblite_runtime_only.jar:bazel-out/x64_windows-fastbuild/bin/external/maven/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar:bazel-out/x64_windows-fastbuild/bin/external/maven/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:bazel-out/x64_windows-fastbuild/bin/external/maven/com/google/errorprone/error_prone_annotations/2.20.0/processed_error_prone_annotations-2.20.0.jar:bazel-out/x64_windows-fastbuild/bin/external …
```
=> Use `;` as classpath separator on Windows

internal/native_image/rules.bzl
Make use of `Args` lazy string formatting to save memory. Also pass in compiler options as repeated flags, not joined on spaces, to prevent issues when compiler options contain spaces.
=> fix(native_image): clean up args building

internal/native_image/rules.bzl
`depset` structures should be kept as flat as possible. C++ toolchain files are also already `depset`s and thus shouldn't be passed into `tools`.
=> fix(native_image): clean up construction of inputs

.bcr/source.template.json, .github/workflows/on.release.yml
Use the artifact download URL for a given rules release, instead of the tag archive. Referenced in bazelbuild/bazel-central-registry#869. Thanks @fmeum!
- fix: set the BCR download endpoint for `rules_graalvm` to the release artifact, which is stable
=> fix: bcr tarball endpoint

internal/graalvm_bindist.bzl
Fixes a bug where only the transitive dependencies of `components` were installed, _not including_ the components actually requested by the user. Fixes and closes #100, which surfaced in #99. Thanks to @mantasindrasius for reporting!
Targeting #80 for merge.
- fix: add requested component to list of effective components installed via bindist
=> fix: install requested components plus deps

MODULE.bazel, MODULE.bazel.lock, README.md, docs/index.md
Fix release for `0.10.0`, which is sadly DOA due to a horrible BCR accident in the workplace. Addresses issues which surfaced in bazelbuild/bazel-central-registry#836.
- fix: bcr publish gone wrong
- chore: bump version → `0.10.1`
- chore: issue new tarballs
- chore: update readme/doc index
=> chore: issue fix release → `0.10.1`

extensions.bzl
Unifying toolchain definitions across transitive modules is hard. By restricting the usage of this tag to the root module, we can come up with better API without breaking potential adopters in the BCR.
=> fix!: restrict `graalvm` tag to the root module

extensions.bzl
In the current Bzlmod setup, all repositories generated by the `graalvm` extension may or may not be used by users and whether they should be can't be predicted based on the given tags: Users that want to generate toolchains need the `<name>_toolchains` repo, users that rely on SDK files need the `<name>` repo.
For now, remove the use of `module_ctx.extension_metadata` so that no warning is shown when users register toolchains in `<name>_toolchains`. In the future, we should improve the way toolchains are registered with Bzlmod by automatically registering a toolchain configured via tags.
=> fix: remove `module_ctx.extension_metadata`

internal/native_image/rules.bzl
> From original PR:
Hey, firstly thanks for making this project.
I am using it on windows and was running into an issue where the command used to invoke native-image was too long for windows. It turns out graalvm added support for args files here https://github.com/graalvm/native-build-tools/pull/205 and it wasn't too hard to add support for them here.
Thanks
Ruairidh
cc / @ruwi-next
=> fix(windows): added `use_param_file` for args

MODULE.bazel, internal/deps.bzl, internal/graalvm_bindist.bzl
This reverts commit 3b204f7ee3e756e477d0cb77cae04d89c457cd7d and instead resolves the problem by updating skylib.
=> fix: update skylib to fix Bazel version check for dev builds instead

docs/api/defs.md, graalvm/nativeimage/rules.bzl, internal/native_image/builder.bzl, internal/native_image/common.bzl
The new `profiles` attribute on `native_image` can be used to apply profile-guided optimization.
=> feat: add support for PGO

README.md
As there is no "`archive_override` below" (anymore, presumably).
https://registry.bazel.build/modules/rules_graalvm seems to be live, so "until we go live on BCR" appears outdated.
=> docs: Remove outdated reference to archive_override

.bazelci/presubmit.yml
Fixes for Bazel CI support, which surfaced in bazelbuild/continuous-integration#1724.
- fix: drop bcr test module stanza from bazelci config
- fix: add build/test targets to run in bazelci
=> fix: bazelci support

graalvm/nativeimage/rules.bzl, internal/native_image/builder.bzl, internal/native_image/common.bzl
Similar to the resource configuration flag, this adds the proxy configuration file.
=> Adds the proxy configuration file flag

.bazelci/presubmit.yml, MODULE.bazel, tools/bazel/cache.bazelrc
The codebase now expects Bazel 7, but Bazel CI runs on both 6.x and 7.x.
- fix: drop `6.3.2` from bazelci matrix
=> fix(bazelci): run bazelci against bazel `7.0.0`

.github/workflows/on.pr.yml
For Dependency Review to work properly, one must first publish a Dependency Graph.
- fix: wait for dependency graph to run review
- fix: retry on snapshot warnings for dependency review
=> fix(ci): dependency review needs the graph

example/integration_tests/graalvm-ce-22/WORKSPACE.bazel, example/integration_tests/graalvm-oracle-22/WORKSPACE.bazel, internal/graalvm_bindist_map.bzl, package.json, pnpm-lock.yaml, pom.xml
Adds GraalVM `24.0.1` to the bindist map.
=> GraalVM 24.0.1

internal/native_image/rules.bzl
Hi,
When building for macOS it is often required to set `--macos_minimum_os` to specify the minimum os version to build for. Running a binary on an os built for a later os could mean it could crash when trying to resolve symbols not in this os release. Not setting this will default to the build machine's os version.
Using this with rules_graalvm does not work as you can see when setting `--macos_minimum_os=11.0` and running `otool -l ./bin | grep -B1 -A3 MIN_MAC`.
The solution is to set env var `MACOSX_DEPLOYMENT_TARGET` for xcode to pick up as documented here https://github.com/clj-easy/graal-docs?tab=readme-ov-file#targeting-a-minimum-macos-version
Thanks
=> fix: support macos minimum version

internal/native_image/rules.bzl
See https://github.com/bazelbuild/bazel/issues/22249 for context.
Fixes #458.
=> fix: avoid using deprecated ctx.resolve_tools

internal/native_image/classic.bzl, internal/native_image/rules.bzl
Fixed a bug where data files weren't provided to `inputs`.
=> fix: add data files to inputs

graal/graal.bzl, internal/native_image/builder.bzl, internal/native_image/common.bzl
=> Support a `serialization_configuration` option for `native_image`

internal/native_image/rules.bzl
Images pick up `sun.jnu.encoding` from the host build environment, which thus needs to be UTF-8 to be able to access paths with non-ASCII characters in them on Linux. Since Bazel does not inherit `LC_CTYPE` from the host, the JVM would otherwise default to an ASCII locale.
=> fix: Force `sun.jnu.encoding` to be UTF-8 in images

.gitattributes-release, .github/workflows/deploy.docs.yml
- ossf/scorecard#2489
Includes GitHub workflows in our tarball export, so that Scorecards' scanner action can see them. Creates a `.gitattributes-release` which can be swapped in during releases. Maybe this `.gitattributes` file can be active only for release commits/tags/branches, I'm not sure yet. In the meantime it can document what the attributes were before remediating this bug.
Also fixes some permission isolation for workflows, which should also improve our score now that the workflows will be visible.
=> fix: scorecards attributes with workflows

extensions.bzl
This can be used to switch between Oracle and CE GraalVM via a flag.
=> feat: Allow the `graalvm` extension to create multiple repos
